# Generated by Django 5.0.4 on 2024-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_email_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
