from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt import views as simple_jwt_views
from .views import *
# from .views import UserViewSet, AdminUserView, MyTokenObtainPairView, UsersList

router = DefaultRouter()
#to create admin user, view all, delete and update users
router.register(r'admin-users', AdminUserView, basename='admin-users')

urlpatterns= [
    path("login/", MyTokenObtainPairView.as_view(), name="login"),  
    path("refresh/", simple_jwt_views.TokenRefreshView.as_view(), name="refresh-token"),
    path("verify/", simple_jwt_views.TokenVerifyView.as_view(), name="verify-token"),
    path('register/', UserViewSet.as_view({"post": "create"}), name='register'),
    *router.urls,  # Include URLs generated by the router
    path('view/user/', UserListAndDetail.as_view(), name='user-list'), 
    path('view/user/<int:pk>/', UserListAndDetail.as_view(), name='user-detail'), 
    path('delete/user/<int:pk>/', UserListAndDetail.as_view(), name='delet-user'),  

    path('me/', UserViewSet.as_view({"get": "me", "delete": "me", "patch": "me", "put": "me"}), name='me'),
    path("activation/<str:uid>/<str:token>/", UserViewSet.as_view({"post": "activation"}), name="activation"),       
    path("resend-activation/", UserViewSet.as_view({"post": "resend_activation"}), name="resend-activation"),
    path("forgot-password/", UserViewSet.as_view({"post": "reset_password"}), name="forgot-password"),
    path("password-reset/<str:uid>/<str:token>/", UserViewSet.as_view({"post": "reset_password_confirm"}), name="confirm-password-reset"),
    path("change-password/", UserViewSet.as_view({"post": "set_password"}), name="change-password"),
]
